# analysis/detector.py

import unidecode

# Dicionário que você forneceu (vou chamar de DOMAIN_SYNONYMS)
DOMAIN_SYNONYMS = {
    # LOCALIZAÇÃO E ENDEREÇO
    "red_lobster": ["Red Lobster", "Seafood Restaurant"],
    "applebees": ["Applebee's", "Neighborhood Grill"],
    "chilis": ["Chili's", "Grill & Bar"],
    "tgif": ["TGI Friday's", "Friday's Restaurant"],
    "outback": ["Outback", "Steakhouse"],
    "texas_roadhouse": ["Texas Roadhouse", "Country Restaurant"],
    "longhorn": ["LongHorn", "Steakhouse"],
    "cracker_barrel": ["Cracker Barrel", "Country Store"],
    "denny": ["Denny's", "24 Hour Diner"],
    "ihop": ["IHOP", "International House of Pancakes"],
    "waffle_house": ["Waffle House", "24 Hour Restaurant"],
    "perkins": ["Perkins", "Restaurant & Bakery"],
    "bob_evans": ["Bob Evans", "Farm Restaurant"],
    "golden_corral": ["Golden Corral", "Buffet Restaurant"],
    "hometown_buffet": ["Hometown Buffet", "Family Buffet"],
    "ryans": ["Ryan's", "Buffet Restaurant"],
    "sizzler": ["Sizzler", "Steakhouse"],
    "red_robin": ["Red Robin", "Gourmet Burgers"],
    "hooters": ["Hooters", "Wings Restaurant"],
    "buffalo_wild": ["Buffalo Wild Wings", "Sports Bar"],
    "wing_street": ["Wing Street", "Chicken Wings"],
    "wingstop": ["Wingstop", "Wing Restaurant"],
    "el_pollo": ["El Pollo Loco", "Flame-Grilled Chicken"],
    "boston_market": ["Boston Market", "Rotisserie Chicken"],
    "kenny_rogers": ["Kenny Rogers Roasters", "Roasted Chicken"],
    "raising_canes": ["Raising Cane's", "Chicken Fingers"],
    "zaxbys": ["Zaxby's", "Chicken & Things"],
    "bojangles": ["Bojangles", "Chicken & Biscuits"],
    "el_pollo_tropical": ["Pollo Tropical", "Caribbean Grilled Chicken"],
    "panda_inn": ["Panda Inn", "Chinese Restaurant"],
    "pei_wei_kitchen": ["Pei Wei Asian Kitchen", "Asian Fast Casual"],
    "pf_changs_bistro": ["P.F. Chang's China Bistro", "Asian Restaurant"],
    "pick_up_stix_asian": ["Pick Up Stix", "Fresh Asian Flavors"],
    "yoshinoya": ["Yoshinoya", "Japanese Fast Food"],
    "teriyaki_madness": ["Teriyaki Madness", "Japanese Grill"],
    "sarku_japan": ["Sarku Japan", "Japanese Fast Food"],
    "sbarro_italian": ["Sbarro Italian Eatery", "New York Pizza"],
    "fazolis": ["Fazoli's", "Fast Italian"],
    "olive_garden_italian": ["Olive Garden Italian Restaurant"],
    "macaroni_grill": ["Romano's Macaroni Grill", "Italian Restaurant"],
    "carrabbas": ["Carrabba's Italian Grill"],
    "maggianos": ["Maggiano's Little Italy"],
    "buca_di_beppo": ["Buca di Beppo", "Authentic Italian"],
    "bertuccis": ["Bertucci's", "Brick Oven Pizza"],
    "uno_chicago": ["Uno Chicago Grill", "Deep Dish Pizza"],
    "papa_murphys": ["Papa Murphy's", "Take N' Bake Pizza"],
    "casey_general": ["Casey's General Store", "Gas Station Food"],
    "wawa": ["Wawa", "Convenience Store"],
    "sheetz": ["Sheetz", "Made to Order Food"],
    "quiktrip": ["QuikTrip", "QT", "Gas Station"],
    "racetrac": ["RaceTrac", "Gas Station Store"],
    "circle_k": ["Circle K", "Convenience Store"],
    "seven_eleven": ["7-Eleven", "7-11", "Convenience Store"],
    "speedway": ["Speedway", "Gas Station"],
    "valero": ["Valero", "Corner Store"],
    "shell": ["Shell", "Gas Station"],
    "bp": ["BP", "Gas Station"],
    "exxon": ["ExxonMobil", "Gas Station"],
    "chevron": ["Chevron", "Gas Station"],
    "mobil": ["Mobil", "Gas Station"],
    "texaco": ["Texaco", "Gas Station"],
    "citgo": ["Citgo", "Gas Station"],
    "sunoco": ["Sunoco", "Gas Station"],
    "marathon": ["Marathon", "Gas Station"],
    "phillips_66": ["Phillips 66", "Gas Station"],
    "conoco": ["ConocoPhillips", "Gas Station"],
    # MARCAS E CONCEITOS BRASILEIROS
    "batata_inglesa": ["Batata Inglesa", "Potato Restaurant"],
    "viena": ["Viena", "Viena Cafe", "Viena Express"],
    "beer_co": ["Beer & Co", "Beer Company", "Cervejaria"],
    "black_coffee": ["Black Coffee", "Black Coffe", "Café Preto"],
    "sports_bar": ["Sports Bar", "Bar Esportivo", "Sports Lounge"],
    "food_hall": ["Food Hall", "Hall de Alimentação", "Praça de Alimentação"],
    "snacks": ["Snacks", "Lanches", "Salgadinhos", "Petiscos"],
    "express": ["Express", "Rápido", "Quick Service"],
    "gourmet": ["Gourmet", "Premium", "Especializado"],
    "tradicional": ["Tradicional", "Traditional", "Clássico"],
    "regional": ["Regional", "Local", "Típico"],
    "internacional": ["Internacional", "International", "Étnico"],
    "fusion": ["Fusion", "Fusão", "Criativo"],
    "contemporaneo": ["Contemporâneo", "Modern", "Atual"],
    "rustico": ["Rústico", "Rustic", "Country"],
    "urbano": ["Urbano", "Urban", "City"],
    "familiar": ["Familiar", "Family", "Para Família"],
    "executivo": ["Executivo", "Executive", "Business"],
    "casual": ["Casual", "Informal", "Descontraído"],
    "sofisticado": ["Sofisticado", "Sophisticated", "Upscale"],
    "popular": ["Popular", "Acessível", "Econômico"],
    "self_service": ["Self Service", "Auto Atendimento", "Buffet Livre"],
    "la_carte": ["À La Carte", "Cardápio", "Menu"],
    "rodizio": ["Rodízio", "All You Can Eat", "Livre"],
    "degustacao": ["Degustação", "Tasting", "Prova"],
    "temático": ["Temático", "Themed", "Concept"],
    "sazonal": ["Sazonal", "Seasonal", "Temporada"],
    "vegano": ["Vegano", "Vegan", "Plant Based"],
    "vegetariano": ["Vegetariano", "Vegetarian", "Veggie"],
    "organico_restaurante": ["Orgânico", "Organic", "Natural"],
    "sem_gluten": ["Sem Glúten", "Gluten Free", "Celíaco"],
    "low_carb": ["Low Carb", "Baixo Carboidrato", "Keto"],
    "light": ["Light", "Diet", "Leve"],
    "fitness": ["Fitness", "Saudável", "Healthy"],
    "comfort_food": ["Comfort Food", "Comida Caseira", "Tradicional"],
    "street_food": ["Street Food", "Comida de Rua", "Food Truck"],
    "delivery_only": ["Delivery Only", "Só Delivery", "Ghost Kitchen"],
    "dark_kitchen": ["Dark Kitchen", "Cozinha Fantasma", "Virtual Restaurant"],
    "cloud_kitchen": ["Cloud Kitchen", "Cozinha Virtual"],
    # TIPOS DE ESTABELECIMENTOS
    "estabelecimento": ["Estabelecimento", "Establishment", "Business"],
    "comercio_estabelecimento": ["Comércio", "Commerce", "Commercial"],
    "servico_estabelecimento": ["Serviço", "Service", "Service Provider"],
    "industria": ["Indústria", "Industry", "Manufacturing"],
    "escritorio": ["Escritório", "Office", "Corporate"],
    "consultorio": ["Consultório", "Clinic", "Medical Office"],
    "clinica": ["Clínica", "Clinic", "Medical Center"],
    "hospital": ["Hospital", "Medical Center", "Healthcare"],
    "farmacia": ["Farmácia", "Pharmacy", "Drugstore"],
    "laboratorio": ["Laboratório", "Laboratory", "Lab"],
    "escola_estabelecimento": ["Escola", "School", "Educational"],
    "universidade_estabelecimento": ["Universidade", "University", "College"],
    "banco_estabelecimento": ["Banco", "Bank", "Financial"],
    "agencia_bancaria": ["Agência Bancária", "Bank Branch"],
    "posto_gasolina": ["Posto de Gasolina", "Gas Station", "Fuel Station"],
    "oficina": ["Oficina", "Workshop", "Garage"],
    "concessionaria": ["Concessionária", "Dealership", "Car Dealer"],
    "hotel": ["Hotel", "Motel", "Hospedagem"],
    "pousada": ["Pousada", "Inn", "Bed & Breakfast"],
    "resort": ["Resort", "Resort Hotel"],
    "hostel": ["Hostel", "Youth Hostel"],
    "academia": ["Academia", "Gym", "Fitness Center"],
    "salao_beleza": ["Salão de Beleza", "Beauty Salon", "Hair Salon"],
    "barbearia": ["Barbearia", "Barbershop", "Barber"],
    "estetica": ["Estética", "Aesthetic", "Beauty Center"],
    "spa": ["Spa", "Day Spa", "Wellness Center"],
    "lavanderia": ["Lavanderia", "Laundry", "Dry Cleaning"],
    "pet_shop": ["Pet Shop", "Pet Store", "Animal Store"],
    "veterinaria": ["Veterinária", "Veterinary", "Animal Clinic"],
    "farmacia_veterinaria": ["Farmácia Veterinária", "Veterinary Pharmacy"],
    "floricultura": ["Floricultura", "Flower Shop", "Florist"],
    "funeraria": ["Funerária", "Funeral Home", "Mortuary"],
    "cartorio": ["Cartório", "Notary", "Registry Office"],
    "despachante": ["Despachante", "Document Service", "Administrative Service"],
    "correios": ["Correios", "Post Office", "Mail Service"],
    "transportadora_estabelecimento": ["Transportadora", "Shipping Company", "Logistics"],
    "seguradora": ["Seguradora", "Insurance Company"],
    "imobiliaria": ["Imobiliária", "Real Estate", "Property"],
    "construtora": ["Construtora", "Construction Company", "Builder"],
    "engenharia": ["Engenharia", "Engineering", "Engineering Firm"],
    "arquitetura": ["Arquitetura", "Architecture", "Architectural Firm"],
    "advocacia": ["Advocacia", "Law Firm", "Legal Services"],
    "contabilidade_estabelecimento": ["Contabilidade", "Accounting Firm", "CPA"],
    "consultoria": ["Consultoria", "Consulting", "Advisory"],
    "agencia_publicidade": ["Agência de Publicidade", "Advertising Agency"],
    "grafica": ["Gráfica", "Print Shop", "Printing"],
    "editora": ["Editora", "Publisher", "Publishing House"],
    "livraria": ["Livraria", "Bookstore", "Book Shop"],
    "biblioteca": ["Biblioteca", "Library"],
    "museu": ["Museu", "Museum"],
    "galeria": ["Galeria", "Gallery", "Art Gallery"],
    "teatro": ["Teatro", "Theater", "Playhouse"],
    "cinema": ["Cinema", "Movie Theater", "Movies"],
    "casa_shows": ["Casa de Shows", "Concert Hall", "Music Venue"],
    "clube": ["Clube", "Club", "Social Club"],
    "associacao": ["Associação", "Association", "Society"],
    "fundacao_estabelecimento": ["Fundação", "Foundation", "Charity"],
    "ong": ["ONG", "NGO", "Non-Profit"],
    "igreja": ["Igreja", "Church", "Religious"],
    "templo": ["Templo", "Temple", "Religious Center"],
    "sindicato": ["Sindicato", "Union", "Trade Union"],
    "cooperativa": ["Cooperativa", "Cooperative", "Co-op"],
    "condominio": ["Condomínio", "Condominium", "Housing Complex"],
    "residencial": ["Residencial", "Residential", "Housing"],
    "comercial_tipo": ["Comercial", "Commercial", "Business"],
    "industrial_tipo": ["Industrial", "Industrial", "Manufacturing"],
    "misto": ["Misto", "Mixed Use", "Combined"],
    # ALIMENTAÇÃO E RESTAURANTES
    "restaurante": ["Restaurante", "Restaurant", "Food Service", "Eating Place"],
    "lanchonete": ["Lanchonete", "Snack Bar", "Fast Food", "Quick Service"],
    "cafeteria": ["Cafeteria", "Cafe", "Coffee Shop", "Coffee House"],
    "cafe": ["Café", "Coffee", "Coffee Shop", "Cafe"],
    "bar": ["Bar", "Pub", "Tavern", "Sports Bar"],
    "pizzaria": ["Pizzaria", "Pizza", "Pizza Place", "Pizza Hut"],
    "hamburgueria": ["Hamburgueria", "Burger", "Hamburger", "Burger Joint"],
    "churrascaria": ["Churrascaria", "BBQ", "Steakhouse", "Grill"],
    "sorveteria": ["Sorveteria", "Ice Cream", "Gelato", "Ice Cream Shop"],
    "padaria": ["Padaria", "Bakery", "Bread Shop", "Bakehouse"],
    "confeitaria": ["Confeitaria", "Pastry Shop", "Cake Shop", "Confectionery"],
    "doceria": ["Doceria", "Sweet Shop", "Candy Store", "Dessert Shop"],
    "açaiteria": ["Açaiteria", "Acai Bowl", "Acai Shop"],
    "rotisseria": ["Rotisseria", "Rotisserie", "Roasted Food"],
    "fast_food": ["Fast Food", "Quick Service", "QSR", "Fast Casual"],
    "casual_dining": ["Casual Dining", "Full Service", "Table Service"],
    "fine_dining": ["Fine Dining", "Upscale", "Gourmet"],
    "buffet": ["Buffet", "Self Service", "All You Can Eat"],
    "delivery": ["Delivery", "Entrega", "Food Delivery"],
    "drive_thru": ["Drive Thru", "Drive Through", "Auto Atendimento"],
    "take_away": ["Take Away", "Para Levar", "Takeout"],
    "food_truck": ["Food Truck", "Truck de Comida", "Mobile Food"],
    "catering": ["Catering", "Buffet", "Event Food Service"],
    "cozinha": ["Cozinha", "Kitchen", "Cooking Area"],
    "cozinha_industrial": ["Cozinha Industrial", "Commercial Kitchen"],
    "area_producao": ["Área de Produção", "Production Area", "Prep Area"],
    "estoque_alimentos": ["Estoque de Alimentos", "Food Storage", "Food Inventory"],
    "freezer": ["Freezer", "Congelador", "Frozen Storage"],
    "geladeira": ["Geladeira", "Refrigerator", "Cooler"],
    "balcao": ["Balcão", "Counter", "Service Counter"],
    "caixa_restaurante": ["Caixa", "Cashier", "Point of Sale", "POS"],
    "cardapio": ["Cardápio", "Menu", "Food Menu"],
    "prato": ["Prato", "Dish", "Plate", "Food Item"],
    "bebida": ["Bebida", "Drink", "Beverage"],
    "sobremesa": ["Sobremesa", "Dessert", "Sweet"],
    "entrada": ["Entrada", "Appetizer", "Starter"],
    "prato_principal": ["Prato Principal", "Main Course", "Entree"],
    "ingrediente": ["Ingrediente", "Ingredient", "Component"],
    "receita": ["Receita", "Recipe", "Formula"],
    "porcao": ["Porção", "Portion", "Serving Size"],
    "combo": ["Combo", "Meal Deal", "Package"],
    "promocao_alimentacao": ["Promoção", "Special Offer", "Food Deal"],
    "happy_hour": ["Happy Hour", "Hora Feliz", "Drink Special"],
    # VAREJO E COMÉRCIO
    "varejo": ["Varejo", "Retail", "Commerce", "Commercial"],
    "atacado": ["Atacado", "Wholesale", "Bulk Sales"],
    "comercio": ["Comércio", "Commerce", "Trade", "Business"],
    "venda": ["Venda", "Sale", "Sales Transaction"],
    "compra": ["Compra", "Purchase", "Buy"],
    "mercadoria": ["Mercadoria", "Merchandise", "Goods", "Products"],
    "produto_comercial": ["Produto", "Product", "Item", "Merchandise"],
    "categoria_produto": ["Categoria de Produto", "Product Category", "Item Category"],
    "subcategoria": ["Subcategoria", "Subcategory", "Product Subcategory"],
    "linha_produto": ["Linha de Produto", "Product Line", "Brand Line"],
    "marca_produto": ["Marca", "Brand", "Product Brand"],
    "modelo": ["Modelo", "Model", "Product Model"],
    "cor": ["Cor", "Color", "Product Color"],
    "tamanho": ["Tamanho", "Size", "Product Size"],
    "peso_produto": ["Peso", "Weight", "Product Weight"],
    "dimensoes": ["Dimensões", "Dimensions", "Size Measurements"],
    "embalagem_produto": ["Embalagem", "Packaging", "Package"],
    "unidade_medida": ["Unidade de Medida", "Unit of Measure", "UOM"],
    "preco_unitario": ["Preço Unitário", "Unit Price", "Price per Unit"],
    "preco_venda": ["Preço de Venda", "Selling Price", "Retail Price"],
    "preco_custo": ["Preço de Custo", "Cost Price", "Purchase Price"],
    "margem_lucro": ["Margem de Lucro", "Profit Margin", "Markup"],
    "desconto_produto": ["Desconto", "Discount", "Price Reduction"],
    "promocao_produto": ["Promoção", "Promotion", "Sale"],
    "oferta_produto": ["Oferta", "Offer", "Special Deal"],
    "liquidacao": ["Liquidação", "Clearance", "Close-out Sale"],
    "black_friday": ["Black Friday", "Black Friday Sale"],
    "cyber_monday": ["Cyber Monday", "Online Sale Day"],
    "sazonalidade": ["Sazonalidade", "Seasonality", "Seasonal"],
    "lancamento_produto": ["Lançamento", "Launch", "New Product"],
    "novidade": ["Novidade", "New Item", "Latest Product"],
    "bestseller": ["Bestseller", "Top Seller", "Best Selling"],
    "exclusivo": ["Exclusivo", "Exclusive", "Limited Edition"],
    "limitado": ["Limitado", "Limited", "Limited Quantity"],
    "importado": ["Importado", "Imported", "International"],
    "nacional": ["Nacional", "National", "Domestic"],
    "organico": ["Orgânico", "Organic", "Natural"],
    "artesanal": ["Artesanal", "Handmade", "Craft"],
    "premium": ["Premium", "High-end", "Luxury"],
    "basico": ["Básico", "Basic", "Standard"],
    "economico": ["Econômico", "Economy", "Budget"],
    # FRANQUIAS ESPECÍFICAS
    "kfc": ["KFC", "Kentucky Fried Chicken", "Frango Frito"],
    "pizza_hut": ["Pizza Hut", "Pizza Hut Restaurant"],
    "mcdonalds": ["McDonald's", "McDonalds", "Mc Donald's"],
    "burger_king": ["Burger King", "BK", "Burger King Restaurant"],
    "subway": ["Subway", "Subway Sandwiches"],
    "starbucks": ["Starbucks", "Starbucks Coffee"],
    "dunkin": ["Dunkin", "Dunkin' Donuts", "Dunkin Donuts"],
    "taco_bell": ["Taco Bell", "Taco Bell Mexican"],
    "dominos": ["Domino's", "Dominos Pizza", "Domino's Pizza"],
    "papa_johns": ["Papa John's", "Papa Johns Pizza"],
    "tim_hortons": ["Tim Hortons", "Tim Hortons Coffee"],
    "wendys": ["Wendy's", "Wendys Restaurant"],
    "dairy_queen": ["Dairy Queen", "DQ", "Ice Cream"],
    "baskin_robbins": ["Baskin Robbins", "31 Flavors"],
    "cinnabon": ["Cinnabon", "Cinnamon Rolls"],
    "auntie_annes": ["Auntie Anne's", "Pretzel"],
    "cold_stone": ["Cold Stone", "Cold Stone Creamery"],
    "orange_julius": ["Orange Julius", "Smoothies"],
    "sbarro": ["Sbarro", "Italian Fast Food"],
    "panda_express": ["Panda Express", "Chinese Fast Food"],
    "chipotle": ["Chipotle", "Mexican Grill"],
    "five_guys": ["Five Guys", "Burger and Fries"],
    "shake_shack": ["Shake Shack", "Burgers and Shakes"],
    "in_n_out": ["In-N-Out", "In N Out Burger"],
    "white_castle": ["White Castle", "Slider Burgers"],
    "churchs": ["Church's", "Church's Chicken"],
    "popeyes": ["Popeyes", "Popeyes Chicken"],
    "long_john": ["Long John Silver's", "Seafood"],
    "arbys": ["Arby's", "Roast Beef"],
    "hardees": ["Hardee's", "Burger Restaurant"],
    "carls_jr": ["Carl's Jr", "Burger Chain"],
    "jack_in_box": ["Jack in the Box", "Fast Food"],
    "del_taco": ["Del Taco", "Mexican Food"],
    "qdoba": ["Qdoba", "Mexican Grill"],
    "moes": ["Moe's", "Southwest Grill"],
    "panera": ["Panera", "Bread Company"],
    "jimmy_johns": ["Jimmy John's", "Gourmet Sandwiches"],
    "quiznos": ["Quiznos", "Toasted Subs"],
    "potbelly": ["Potbelly", "Sandwich Shop"],
    "blimpie": ["Blimpie", "Sub Sandwiches"],
    "firehouse": ["Firehouse Subs", "Hot Subs"],
    "jersey_mikes": ["Jersey Mike's", "Sub Shop"],
    "which_wich": ["Which Wich", "Superior Sandwiches"],
    "noodles": ["Noodles & Company", "Noodle Restaurant"],
    "pei_wei": ["Pei Wei", "Asian Kitchen"],
    "pick_up_stix": ["Pick Up Stix", "Asian Cuisine"],
    "pf_changs": ["P.F. Chang's", "Asian Bistro"],
    "benihana": ["Benihana", "Japanese Steakhouse"],
    "olive_garden": ["Olive Garden", "Italian Restaurant"],
    # LOCALIZAÇÃO E ENDEREÇO
    "cep": ["CEP", "Código Postal", "Postal Code", "ZIP Code", "Zip"],
    "cidade": ["Cidade", "Município", "City", "Localidade", "Municipal"],
    "estado": ["Estado", "UF", "Unidade Federativa", "State", "Província", "Federação"],
    "pais": ["País", "Country", "Nação", "Nation", "Nacionalidade"],
    "endereco": [
        "Endereço",
        "Address",
        "Logradouro",
        "Rua",
        "Street",
        "Avenida",
        "Av",
        "Endereços",
    ],
    "endereco_completo": ["Endereço Completo", "Full Address", "Complete Address"],
    "logradouro": ["Logradouro", "Street", "Avenue", "Road", "Public Place"],
    "tipo_logradouro": ["Tipo de Logradouro", "Street Type", "Address Type"],
    "rua": ["Rua", "Street", "St", "R"],
    "avenida": ["Avenida", "Avenue", "Ave", "Av"],
    "alameda": ["Alameda", "Alameda", "Al"],
    "rodovia": ["Rodovia", "Highway", "Road", "BR", "Highway"],
    "estrada": ["Estrada", "Road", "Country Road"],
    "travessa": ["Travessa", "Alley", "Cross Street"],
    "praca": ["Praça", "Square", "Plaza", "Pc"],
    "largo": ["Largo", "Square", "Plaza"],
    "quadra": ["Quadra", "Block", "City Block"],
    "lote_endereco": ["Lote", "Lot", "Plot"],
    "km": ["KM", "Quilômetro", "Kilometer", "Mile Marker"],
    "sn": ["S/N", "S/Nº", "Sem Número", "No Number", "Without Number"],
    "bairro": ["Bairro", "Distrito", "Neighborhood", "District", "Zone", "Area"],
    "numero": ["Número", "Number", "Nº", "No", "Num", "#"],
    "complemento": ["Complemento", "Complement", "Observação", "Obs", "Adicional"],
    "regiao": ["Região", "Region", "Zona", "Zone", "Area", "Territory"],
    "zona": ["Zona", "Zone", "Area", "District"],
    "setor_local": ["Setor", "Sector", "Area", "Zone"],
    "coordenadas": ["Coordenadas", "Coordinates", "GPS", "Latitude", "Longitude"],
    "latitude": ["Latitude", "Lat", "GPS Latitude"],
    "longitude": ["Longitude", "Long", "GPS Longitude"],
    "referencias": ["Referências", "References", "Ponto de Referência", "Landmark"],
    "ponto_referencia": ["Ponto de Referência", "Landmark", "Reference Point"],
    # NEGÓCIO E EMPRESA
    "loja": ["Loja", "Franquia", "Nome", "Store", "Franchise", "Unidade", "Shop", "Lojas"],
    "nome_loja": ["Nome da Loja", "Store Name", "Loja Nome", "Nome Unidade", "Unit Name"],
    "codigo_loja": ["Código da Loja", "Store Code", "Código Unidade", "Unit Code", "Store ID"],
    "numero_loja": ["Número da Loja", "Store Number", "Loja Número", "Unit Number"],
    "categoria": ["Categoria", "Tipo", "Segmento", "Category", "Type", "Classification"],
    "conceito": ["Conceito", "Concept", "Store Concept", "Format"],
    "formato": ["Formato", "Format", "Store Format", "Layout"],
    "bandeira": ["Bandeira", "Brand", "Flag", "Store Brand"],
    "rede_varejo": ["Rede", "Chain", "Network", "Retail Chain"],
    "empresa": ["Empresa", "Company", "Corporação", "Organização", "Corporation", "Firm"],
    "razao_social": ["Razão Social", "Corporate Name", "Nome Empresarial", "Legal Name"],
    "nome_fantasia": ["Nome Fantasia", "Trade Name", "Brand Name", "Commercial Name"],
    "cnpj": ["CNPJ", "CPF", "Tax ID", "Corporate ID", "Federal ID"],
    "inscricao_estadual": ["Inscrição Estadual", "IE", "State Registration", "State ID"],
    "inscricao_municipal": ["Inscrição Municipal", "IM", "Municipal Registration"],
    "filial": ["Filial", "Branch", "Subsidiary", "Sucursal", "Unit"],
    "matriz": ["Matriz", "Headquarters", "Head Office", "Main Office"],
    "franqueado": ["Franqueado", "Franchisee", "Franchise Owner"],
    "franqueador": ["Franqueador", "Franchisor", "Franchise Company"],
    "master_franquia": ["Master Franquia", "Master Franchise", "Regional Franchise"],
    "area_restrita": ["Área Restrita", "Restricted Area", "Security Area"],
    "terminal": ["Terminal", "Terminal Number", "Airport Terminal"],
    "pier": ["Pier", "Terminal Pier", "Airport Pier"],
    "pavilhao": ["Pavilhão", "Pavilion", "Hall"],
    "pavimento": ["Pavimento", "Floor", "Level"],
    "andar": ["Andar", "Floor", "Story"],
    "sala": ["Sala", "Room", "Suite"],
    "loja_numero": ["Número da Loja", "Shop Number", "Unit Number"],
    "box": ["Box", "Kiosk", "Stand"],
    "quiosque": ["Quiosque", "Kiosk", "Stand"],
    "praca_alimentacao": ["Praça de Alimentação", "Food Court", "Food Hall"],
    "food_court": ["Food Court", "Praça de Alimentação", "Food Hall"],
    "shopping": ["Shopping", "Mall", "Shopping Center"],
    "shopping_center": ["Shopping Center", "Mall", "Commercial Center"],
    "centro_comercial": ["Centro Comercial", "Commercial Center", "Business Center"],
    "aeroporto": ["Aeroporto", "Airport", "International Airport"],
    "rodoviaria": ["Rodoviária", "Bus Station", "Bus Terminal"],
    "estacao": ["Estação", "Station", "Transport Station"],
    "metro": ["Metrô", "Metro", "Subway"],
    "trem": ["Trem", "Train", "Railway"],
    "porte": ["Porte", "Size", "Scale", "Company Size"],
    "ramo": ["Ramo", "Business Line", "Industry", "Sector"],
    "atividade": ["Atividade", "Activity", "Business Activity", "Operation"],
    "fundacao": ["Fundação", "Founded", "Establishment", "Creation Date"],
    "capital_social": ["Capital Social", "Share Capital", "Equity Capital"],
    # TECNOLOGIA DA INFORMAÇÃO (TI)
    "sistema": ["Sistema", "System", "Software", "Application", "App"],
    "servidor": ["Servidor", "Server", "Host", "Machine", "Node"],
    "banco_dados": ["Banco de Dados", "Database", "DB", "Schema", "DataBase"],
    "aplicacao": ["Aplicação", "Application", "App", "Sistema", "Program"],
    "usuario": ["Usuário", "User", "Login", "Account", "Username"],
    "senha": ["Senha", "Password", "Pass", "Authentication", "Auth"],
    "ip": ["IP", "Endereço IP", "IP Address", "Network Address"],
    "porta": ["Porta", "Port", "Service Port", "TCP Port", "UDP Port"],
    "protocolo": ["Protocolo", "Protocol", "Communication Protocol"],
    "api": ["API", "Interface", "Web Service", "Endpoint", "REST"],
    "versao": ["Versão", "Version", "Release", "Build", "Revision"],
    "licenca": ["Licença", "License", "Subscription", "Plan", "Key"],
    "backup": ["Backup", "Cópia de Segurança", "Restore Point", "Archive"],
    "log": ["Log", "Registro", "Audit Trail", "Event Log", "History"],
    "erro": ["Erro", "Error", "Exception", "Bug", "Issue"],
    "status": ["Status", "Estado", "Condition", "State", "Situation"],
    "tipo_dispositivo": ["Tipo de Dispositivo", "Device Type", "Hardware Type"],
    "so": ["Sistema Operacional", "SO", "OS", "Operating System"],
    "cpu": ["CPU", "Processador", "Processor", "Core", "Microprocessor"],
    "memoria": ["Memória", "Memory", "RAM", "Storage", "Cache"],
    "disco": ["Disco", "Hard Drive", "Storage", "HD", "SSD", "HDD"],
    "rede": ["Rede", "Network", "LAN", "WAN", "WiFi", "Ethernet"],
    "firewall": ["Firewall", "Security", "Protection", "Firewall Rules"],
    "antivirus": ["Antivírus", "Antivirus", "Security Software", "Protection"],
    "dominio": ["Domínio", "Domain", "URL", "Website", "Site"],
    "ssl": ["SSL", "Certificate", "Security Certificate", "HTTPS"],
    "ftp": ["FTP", "File Transfer", "SFTP", "Transfer Protocol"],
    "vpn": ["VPN", "Virtual Private Network", "Tunnel"],
    "proxy": ["Proxy", "Gateway", "Intermediary"],
    "dns": ["DNS", "Domain Name System", "Name Server"],
    "dhcp": ["DHCP", "Dynamic IP", "IP Assignment"],
    "mac_address": ["MAC Address", "Physical Address", "Hardware Address"],
    # FINANÇAS
    "receita_financeira": ["Receita", "Revenue", "Income", "Faturamento", "Earnings"],
    "despesa": ["Despesa", "Expense", "Cost", "Gasto", "Expenditure"],
    "lucro": ["Lucro", "Profit", "Gain", "Earnings", "Net Income"],
    "prejuizo": ["Prejuízo", "Loss", "Deficit", "Negative Result"],
    "investimento": ["Investimento", "Investment", "Capital", "Application"],
    "ativo": ["Ativo", "Asset", "Property", "Resource"],
    "passivo": ["Passivo", "Liability", "Debt", "Obligation"],
    "patrimonio": ["Patrimônio", "Equity", "Net Worth", "Assets"],
    "capital": ["Capital", "Capital Stock", "Equity", "Investment"],
    "divida": ["Dívida", "Debt", "Loan", "Liability", "Borrowing"],
    "credito": ["Crédito", "Credit", "Loan", "Financing"],
    "debito": ["Débito", "Debit", "Charge", "Withdrawal"],
    "saldo": ["Saldo", "Balance", "Amount", "Remaining"],
    "fluxo_caixa": ["Fluxo de Caixa", "Cash Flow", "Cash Movement"],
    "conta": ["Conta", "Account", "Account Number", "Banking Account"],
    "banco": ["Banco", "Bank", "Financial Institution"],
    "agencia": ["Agência", "Branch", "Agency", "Bank Branch"],
    "juros": ["Juros", "Interest", "Interest Rate", "Finance Charge"],
    "taxa": ["Taxa", "Rate", "Fee", "Charge", "Commission"],
    "multa": ["Multa", "Fine", "Penalty", "Late Fee"],
    "desconto": ["Desconto", "Discount", "Rebate", "Reduction"],
    "pagamento": ["Pagamento", "Payment", "Settlement", "Transaction"],
    "recebimento": ["Recebimento", "Receipt", "Collection", "Income"],
    "fatura": ["Fatura", "Invoice", "Bill", "Statement"],
    "nota_fiscal": ["Nota Fiscal", "Invoice", "Tax Document", "Fiscal Note"],
    "orcamento": ["Orçamento", "Budget", "Quote", "Estimate"],
    "planejamento": ["Planejamento", "Planning", "Forecast", "Strategy"],
    "projecao": ["Projeção", "Projection", "Forecast", "Prediction"],
    "roi": ["ROI", "Return on Investment", "Retorno sobre Investimento"],
    "margem": ["Margem", "Margin", "Markup", "Profit Margin"],
    "cotacao": ["Cotação", "Quote", "Exchange Rate", "Price Quote"],
    "moeda": ["Moeda", "Currency", "Money", "Cash"],
    "cambio": ["Câmbio", "Exchange", "Currency Exchange"],
    "financiamento": ["Financiamento", "Financing", "Loan", "Credit"],
    "emprestimo": ["Empréstimo", "Loan", "Borrowing", "Credit"],
    "cartao_credito": ["Cartão de Crédito", "Credit Card", "Card"],
    "cheque": ["Cheque", "Check", "Bank Draft"],
    "transferencia": ["Transferência", "Transfer", "Wire Transfer"],
    "deposito_bancario": ["Depósito", "Deposit", "Bank Deposit"],
    "saque": ["Saque", "Withdrawal", "Cash Withdrawal"],
    "pix": ["PIX", "Instant Payment", "Electronic Transfer"],
    "ted": ["TED", "Electronic Transfer", "Bank Transfer"],
    "doc": ["DOC", "Document Transfer", "Bank Document"],
    # ECONOMIA
    "pib": ["PIB", "GDP", "Produto Interno Bruto", "Gross Domestic Product"],
    "inflacao": ["Inflação", "Inflation", "Price Index", "CPI"],
    "deflacao": ["Deflação", "Deflation", "Price Decrease"],
    "crescimento": ["Crescimento", "Growth", "Expansion", "Development"],
    "recessao": ["Recessão", "Recession", "Economic Downturn"],
    "mercado": ["Mercado", "Market", "Marketplace", "Trading"],
    "setor": ["Setor", "Sector", "Industry", "Business Sector"],
    "economia": ["Economia", "Economy", "Economic", "Financial System"],
    "macro": ["Macroeconomia", "Macro", "Macroeconomic"],
    "micro": ["Microeconomia", "Micro", "Microeconomic"],
    "oferta": ["Oferta", "Supply", "Offer", "Availability"],
    "demanda": ["Demanda", "Demand", "Request", "Need"],
    "preco": ["Preço", "Price", "Cost", "Value", "Amount"],
    "custo": ["Custo", "Cost", "Expense", "Price"],
    "valor": ["Valor", "Value", "Worth", "Amount", "Price"],
    "indice": ["Índice", "Index", "Indicator", "Rate"],
    "indicador": ["Indicador", "Indicator", "Metric", "KPI"],
    "balanca_comercial": ["Balança Comercial", "Trade Balance", "Commercial Balance"],
    "exportacao": ["Exportação", "Export", "Outbound Trade", "Foreign Sales"],
    "importacao": ["Importação", "Import", "Inbound Trade", "Foreign Purchase"],
    "cambio_economia": ["Câmbio", "Exchange", "Foreign Exchange", "FX"],
    "bolsa": ["Bolsa", "Stock Exchange", "Market", "Stock Market"],
    "acao": ["Ação", "Stock", "Share", "Equity"],
    "dividendo": ["Dividendo", "Dividend", "Profit Share"],
    "commodities": ["Commodities", "Raw Materials", "Primary Products"],
    "selic": ["SELIC", "Base Interest Rate", "Central Bank Rate"],
    "cdi": ["CDI", "Interbank Rate", "Daily Rate"],
    "ipca": ["IPCA", "Consumer Price Index", "Inflation Index"],
    "igp": ["IGP", "General Price Index"],
    # RECURSOS HUMANOS (RH)
    "funcionario": ["Funcionário", "Employee", "Worker", "Staff", "Personnel"],
    "colaborador": ["Colaborador", "Collaborator", "Team Member", "Associate"],
    "cargo": ["Cargo", "Position", "Job Title", "Role", "Function"],
    "funcao": ["Função", "Function", "Role", "Responsibility"],
    "salario": ["Salário", "Salary", "Wage", "Pay", "Compensation"],
    "remuneracao": ["Remuneração", "Compensation", "Payment", "Remuneration"],
    "beneficio": ["Benefício", "Benefit", "Perk", "Advantage"],
    "ferias": ["Férias", "Vacation", "Holiday", "Leave", "Time Off"],
    "licenca_rh": ["Licença", "Leave", "Time Off", "Absence"],
    "atestado": ["Atestado", "Medical Certificate", "Health Certificate"],
    "falta": ["Falta", "Absence", "No Show", "Missing"],
    "atraso": ["Atraso", "Late", "Delay", "Tardiness"],
    "overtime": ["Hora Extra", "Overtime", "Extra Hours", "Additional Hours"],
    "departamento": ["Departamento", "Department", "Division", "Area"],
    "equipe": ["Equipe", "Team", "Group", "Squad"],
    "gerente": ["Gerente", "Manager", "Supervisor", "Chief"],
    "diretor": ["Diretor", "Director", "Executive", "Head"],
    "presidente": ["Presidente", "President", "CEO", "Chief Executive"],
    "admissao": ["Admissão", "Hiring", "Onboarding", "Employment"],
    "demissao": ["Demissão", "Termination", "Dismissal", "Firing"],
    "rescisao": ["Rescisão", "Contract Termination", "Employment End"],
    "contrato": ["Contrato", "Contract", "Agreement", "Employment Contract"],
    "clt": ["CLT", "Labor Law", "Employment Law", "Work Contract"],
    "pj": ["PJ", "Pessoa Jurídica", "Contractor", "Legal Entity"],
    "terceirizado": ["Terceirizado", "Outsourced", "Contractor", "External"],
    "estagiario": ["Estagiário", "Intern", "Trainee", "Student"],
    "trainee": ["Trainee", "Graduate Program", "Junior Professional"],
    "avaliacao": ["Avaliação", "Performance Review", "Assessment", "Evaluation"],
    "treinamento": ["Treinamento", "Training", "Development", "Course"],
    "capacitacao": ["Capacitação", "Training", "Skill Development", "Qualification"],
    "competencia": ["Competência", "Skill", "Competency", "Ability"],
    "habilidade": ["Habilidade", "Skill", "Ability", "Talent"],
    "experiencia": ["Experiência", "Experience", "Background", "Expertise"],
    "curriculo": ["Currículo", "Resume", "CV", "Curriculum Vitae"],
    "entrevista": ["Entrevista", "Interview", "Meeting", "Assessment"],
    "selecao": ["Seleção", "Selection", "Recruitment", "Hiring Process"],
    "recrutamento": ["Recrutamento", "Recruitment", "Hiring", "Talent Acquisition"],
    "folha_pagamento": ["Folha de Pagamento", "Payroll", "Salary Sheet"],
    "inss": ["INSS", "Social Security", "Social Insurance"],
    "fgts": ["FGTS", "Severance Fund", "Employment Fund"],
    "vale_transporte": ["Vale Transporte", "Transportation Voucher", "Transport Benefit"],
    "vale_refeicao": ["Vale Refeição", "Meal Voucher", "Food Benefit"],
    "vale_alimentacao": ["Vale Alimentação", "Food Voucher", "Grocery Benefit"],
    "plano_saude": ["Plano de Saúde", "Health Insurance", "Medical Plan"],
    "plano_odontologico": ["Plano Odontológico", "Dental Plan", "Dental Insurance"],
    "seguro_vida": ["Seguro de Vida", "Life Insurance", "Life Coverage"],
    "auxilio_creche": ["Auxílio Creche", "Daycare Assistance", "Childcare Benefit"],
    "participacao_lucros": ["Participação nos Lucros", "Profit Sharing", "PLR"],
    "premio": ["Prêmio", "Award", "Bonus", "Prize"],
    "promocao_rh": ["Promoção", "Promotion", "Career Advancement"],
    # VENDAS E MARKETING
    "vendas": ["Vendas", "Sales", "Revenue", "Selling"],
    "cliente": ["Cliente", "Customer", "Client", "Consumer"],
    "prospect": ["Prospect", "Lead", "Potential Customer", "Target"],
    "lead": ["Lead", "Prospect", "Contact", "Potential Client"],
    "campanha": ["Campanha", "Campaign", "Marketing Campaign", "Promotion"],
    "promocao": ["Promoção", "Promotion", "Offer", "Sale"],
    "desconto_marketing": ["Desconto", "Discount", "Sale", "Rebate"],
    "produto": ["Produto", "Product", "Item", "Merchandise"],
    "servico": ["Serviço", "Service", "Solution"],
    "marca": ["Marca", "Brand", "Trademark", "Label"],
    "segmento_marketing": ["Segmento", "Segment", "Target", "Market Segment"],
    "publico_alvo": ["Público Alvo", "Target Audience", "Target Market"],
    "conversion": ["Conversão", "Conversion Rate", "Sales Conversion"],
    "roi_marketing": ["ROI", "Return on Investment", "Marketing ROI"],
    "vendedor": ["Vendedor", "Salesperson", "Sales Rep", "Account Executive"],
    "comissao": ["Comissão", "Commission", "Sales Commission"],
    "meta": ["Meta", "Goal", "Target", "Objective"],
    "pedido": ["Pedido", "Order", "Purchase Order", "Request"],
    "proposta": ["Proposta", "Proposal", "Quote", "Offer"],
    "negociacao": ["Negociação", "Negotiation", "Deal"],
    "fechamento": ["Fechamento", "Closing", "Deal Close", "Sale Close"],
    "pipeline": ["Pipeline", "Sales Pipeline", "Funnel"],
    "crm": ["CRM", "Customer Relationship Management", "Client Management"],
    "seo": ["SEO", "Search Engine Optimization", "Search Optimization"],
    "sem": ["SEM", "Search Engine Marketing", "Paid Search"],
    "email_marketing": ["Email Marketing", "Newsletter", "Email Campaign"],
    "redes_sociais": ["Redes Sociais", "Social Media", "Social Networks"],
    "influencer": ["Influencer", "Digital Influencer", "Content Creator"],
    # PRODUÇÃO E OPERAÇÕES
    "producao": ["Produção", "Production", "Manufacturing", "Output"],
    "operacao": ["Operação", "Operation", "Process", "Activity"],
    "processo": ["Processo", "Process", "Procedure", "Method"],
    "qualidade": ["Qualidade", "Quality", "Standard", "Excellence"],
    "estoque": ["Estoque", "Inventory", "Stock", "Storage"],
    "fornecedor": ["Fornecedor", "Supplier", "Vendor", "Provider"],
    "materia_prima": ["Matéria Prima", "Raw Material", "Input Material"],
    "capacidade": ["Capacidade", "Capacity", "Volume", "Output Capacity"],
    "producao_diaria": ["Produção Diária", "Daily Production", "Daily Output"],
    "eficiencia": ["Eficiência", "Efficiency", "Performance", "Effectiveness"],
    "produtividade": ["Produtividade", "Productivity", "Output Rate"],
    "linha_producao": ["Linha de Produção", "Production Line", "Assembly Line"],
    "maquina": ["Máquina", "Machine", "Equipment", "Machinery"],
    "equipamento": ["Equipamento", "Equipment", "Tool", "Device"],
    "manutencao": ["Manutenção", "Maintenance", "Service", "Repair"],
    "inspecao": ["Inspeção", "Inspection", "Quality Check", "Review"],
    "teste": ["Teste", "Test", "Testing", "Quality Test"],
    "defeito": ["Defeito", "Defect", "Flaw", "Quality Issue"],
    "lote_producao": ["Lote", "Batch", "Lot", "Production Batch"],
    "serial": ["Serial", "Serial Number", "Product Serial"],
    "codigo_barras": ["Código de Barras", "Barcode", "Product Code"],
    "sku": ["SKU", "Stock Keeping Unit", "Product Code"],
    "ncm": ["NCM", "Nomenclatura Comum do Mercosul", "Product Classification"],
    # JURÍDICO E COMPLIANCE
    "contrato_juridico": ["Contrato", "Contract", "Agreement", "Legal Agreement"],
    "lei": ["Lei", "Law", "Regulation", "Legal Requirement"],
    "regulamentacao": ["Regulamentação", "Regulation", "Rule", "Compliance Rule"],
    "compliance": ["Compliance", "Conformidade", "Legal Compliance"],
    "auditoria": ["Auditoria", "Audit", "Review", "Legal Review"],
    "licenca_juridica": ["Licença", "License", "Permit", "Authorization"],
    "alvara": ["Alvará", "Permit", "License", "Municipal License"],
    "processo_juridico": ["Processo", "Legal Process", "Lawsuit", "Legal Case"],
    "tribunal": ["Tribunal", "Court", "Legal Court"],
    "advogado": ["Advogado", "Lawyer", "Attorney", "Legal Counsel"],
    "juridico": ["Jurídico", "Legal", "Law", "Legal Affairs"],
    "legislacao": ["Legislação", "Legislation", "Legal Framework"],
    "norma": ["Norma", "Standard", "Regulation", "Rule"],
    "clausula": ["Cláusula", "Clause", "Contract Term"],
    "termo": ["Termo", "Term", "Agreement Term"],
    "acordo": ["Acordo", "Agreement", "Settlement", "Deal"],
    "arbitragem": ["Arbitragem", "Arbitration", "Mediation"],
    "mediacao": ["Mediação", "Mediation", "Settlement"],
    "multa_juridica": ["Multa", "Fine", "Legal Penalty", "Sanction"],
    "sancao": ["Sanção", "Sanction", "Penalty", "Fine"],
    # LOGÍSTICA E TRANSPORTE
    "entrega": ["Entrega", "Delivery", "Shipment", "Distribution"],
    "frete": ["Frete", "Freight", "Shipping", "Transport Cost"],
    "transportadora": ["Transportadora", "Carrier", "Shipping Company", "Logistics"],
    "veiculo": ["Veículo", "Vehicle", "Transport", "Truck"],
    "rota": ["Rota", "Route", "Path", "Delivery Route"],
    "carga": ["Carga", "Load", "Cargo", "Freight"],
    "peso": ["Peso", "Weight", "Mass"],
    "volume": ["Volume", "Volume", "Size", "Capacity"],
    "prazo": ["Prazo", "Deadline", "Due Date", "Lead Time"],
    "rastreamento": ["Rastreamento", "Tracking", "Trace", "Follow-up"],
    "armazem": ["Armazém", "Warehouse", "Storage", "Distribution Center"],
    "deposito_armazem": ["Depósito", "Warehouse", "Storage Facility"],
    "distribuicao": ["Distribuição", "Distribution", "Delivery Network"],
    "logistica": ["Logística", "Logistics", "Supply Chain"],
    "expedicao": ["Expedição", "Shipping", "Dispatch", "Shipment"],
    "recebimento_logistica": ["Recebimento", "Receiving", "Intake"],
    "conferencia": ["Conferência", "Checking", "Verification", "Inspection"],
    "separacao": ["Separação", "Picking", "Order Picking"],
    "embalagem": ["Embalagem", "Packaging", "Package", "Wrapping"],
    "etiqueta": ["Etiqueta", "Label", "Tag", "Shipping Label"],
    # DATAS E TEMPO
    "data": ["Data", "Date", "Day", "Calendar Date"],
    "hora": ["Hora", "Time", "Hour", "Clock Time"],
    "periodo": ["Período", "Period", "Time Frame", "Duration"],
    "ano": ["Ano", "Year", "Annual"],
    "mes": ["Mês", "Month", "Monthly"],
    "dia": ["Dia", "Day", "Daily"],
    "semana": ["Semana", "Week", "Weekly"],
    "trimestre": ["Trimestre", "Quarter", "Quarterly"],
    "semestre": ["Semestre", "Semester", "Half-year"],
    "bimestre": ["Bimestre", "Bi-monthly", "Two Months"],
    "vencimento": ["Vencimento", "Due Date", "Expiration", "Maturity"],
    "inicio": ["Início", "Start", "Beginning", "Commencement"],
    "fim": ["Fim", "End", "Finish", "Conclusion"],
    "duracao": ["Duração", "Duration", "Length", "Time Span"],
    "cronograma": ["Cronograma", "Schedule", "Timeline", "Timetable"],
    "agenda": ["Agenda", "Schedule", "Calendar", "Appointment"],
    "prazo_final": ["Prazo Final", "Final Deadline", "End Date"],
    "timestamp": ["Timestamp", "Time Stamp", "Date Time"],
    # IDENTIFICAÇÃO E DOCUMENTOS
    "id": ["ID", "Identificação", "Código", "Code", "Identifier"],
    "codigo": ["Código", "Code", "ID", "Reference"],
    "documento": ["Documento", "Document", "Paper", "Record"],
    "cpf": ["CPF", "Tax ID", "Personal ID", "Individual Registration"],
    "cnpj_doc": ["CNPJ", "Corporate Tax ID", "Company Registration"],
    "rg": ["RG", "Identity Card", "ID Card", "National ID"],
    "passaporte": ["Passaporte", "Passport", "Travel Document"],
    "carteira_trabalho": ["Carteira de Trabalho", "Work Permit", "Labor Card"],
    "carteira_motorista": ["Carteira de Motorista", "Driver License", "CNH"],
    "titulo_eleitor": ["Título de Eleitor", "Voter Registration", "Electoral Title"],
    "certidao_nascimento": ["Certidão de Nascimento", "Birth Certificate"],
    "certidao_casamento": ["Certidão de Casamento", "Marriage Certificate"],
    "comprovante_residencia": ["Comprovante de Residência", "Proof of Address"],
    "numero_documento": ["Número do Documento", "Document Number"],
    "orgao_emissor": ["Órgão Emissor", "Issuing Authority", "Issuer"],
    "data_emissao": ["Data de Emissão", "Issue Date", "Issuance Date"],
    "data_validade": ["Data de Validade", "Expiration Date", "Valid Until"],
    # CONTATO E COMUNICAÇÃO
    "telefone": ["Telefone", "Phone", "Tel", "Phone Number"],
    "celular": ["Celular", "Mobile", "Cell Phone", "Mobile Phone"],
    "email": ["Email", "E-mail", "Electronic Mail", "Email Address"],
    "site": ["Site", "Website", "Web", "Homepage"],
    "whatsapp": ["WhatsApp", "WA", "WhatsApp Number"],
    "telegram": ["Telegram", "Telegram Contact"],
    "skype": ["Skype", "Skype ID"],
    "linkedin": ["LinkedIn", "LinkedIn Profile"],
    "facebook": ["Facebook", "Facebook Profile"],
    "instagram": ["Instagram", "Instagram Profile", "IG"],
    "twitter": ["Twitter", "Twitter Profile", "X"],
    "youtube": ["YouTube", "YouTube Channel"],
    "tiktok": ["TikTok", "TikTok Profile"],
    "discord": ["Discord", "Discord Contact"],
    "slack": ["Slack", "Slack Contact"],
    "teams": ["Teams", "Microsoft Teams"],
    "zoom": ["Zoom", "Zoom Meeting"],
    "ramal": ["Ramal", "Extension", "Phone Extension"],
    "fax": ["Fax", "Fax Number"],
    "caixa_postal": ["Caixa Postal", "PO Box", "Mail Box"],
    # EDUCAÇÃO E FORMAÇÃO
    "educacao": ["Educação", "Education", "Learning", "Academic Background"],
    "formacao": ["Formação", "Education", "Degree", "Academic Formation"],
    "curso": ["Curso", "Course", "Program", "Academic Course"],
    "certificacao": ["Certificação", "Certification", "Certificate", "Professional Certificate"],
    "diploma": ["Diploma", "Degree", "Academic Diploma"],
    "universidade": ["Universidade", "University", "College", "Higher Education"],
    "faculdade": ["Faculdade", "College", "Faculty", "School"],
    "escola": ["Escola", "School", "Educational Institution"],
    "instituto": ["Instituto", "Institute", "Technical School"],
    "nivel": ["Nível", "Level", "Grade", "Academic Level"],
    "nota": ["Nota", "Grade", "Score", "Mark"],
    "disciplina": ["Disciplina", "Subject", "Course Subject"],
    "materia": ["Matéria", "Subject", "Course Material"],
    "professor": ["Professor", "Teacher", "Instructor"],
    "aluno": ["Aluno", "Student", "Pupil"],
    "graduacao": ["Graduação", "Undergraduate", "Bachelor Degree"],
    "pos_graduacao": ["Pós-Graduação", "Graduate", "Postgraduate"],
    "mestrado": ["Mestrado", "Masters", "Masters Degree"],
    "doutorado": ["Doutorado", "PhD", "Doctorate"],
    "especializacao": ["Especialização", "Specialization", "Professional Course"],
    "mba": ["MBA", "Master of Business Administration"],
    "tecnico": ["Técnico", "Technical", "Technical Course"],
    "profissionalizante": ["Profissionalizante", "Professional", "Vocational"],
    "ead": ["EAD", "Distance Learning", "Online Education"],
    "presencial": ["Presencial", "In-Person", "Face-to-Face"],
    "hibrido": ["Híbrido", "Hybrid", "Blended Learning"],
    # SAÚDE E SEGURANÇA
    "saude": ["Saúde", "Health", "Healthcare", "Medical"],
    "seguranca": ["Segurança", "Security", "Safety", "Protection"],
    "medicina_trabalho": ["Medicina do Trabalho", "Occupational Health", "Work Medicine"],
    "exame_medico": ["Exame Médico", "Medical Exam", "Health Check"],
    "exame_admissional": ["Exame Admissional", "Pre-employment Medical"],
    "exame_periodico": ["Exame Periódico", "Periodic Medical Exam"],
    "exame_demissional": ["Exame Demissional", "Exit Medical Exam"],
    "acidente": ["Acidente", "Accident", "Incident", "Work Accident"],
    "acidente_trabalho": ["Acidente de Trabalho", "Work Accident", "Occupational Accident"],
    "epi": ["EPI", "Personal Protective Equipment", "Safety Equipment"],
    "epc": ["EPC", "Collective Protective Equipment"],
    "cipa": ["CIPA", "Safety Committee", "Accident Prevention Committee"],
    "brigada": ["Brigada", "Emergency Team", "Fire Brigade"],
    "sesmt": ["SESMT", "Occupational Safety Service"],
    "nr": ["NR", "Regulatory Standard", "Safety Standard"],
    "cat": ["CAT", "Work Accident Report"],
    "pcmso": ["PCMSO", "Medical Control Program"],
    "ppra": ["PPRA", "Environmental Risk Prevention Program"],
    "ltcat": ["LTCAT", "Technical Report on Working Conditions"],
    "ppp": ["PPP", "Occupational Profile Form"],
    "aso": ["ASO", "Occupational Health Certificate"],
    "laudo": ["Laudo", "Technical Report", "Medical Report"],
    "risco": ["Risco", "Risk", "Hazard", "Safety Risk"],
    "periculosidade": ["Periculosidade", "Hazard Pay", "Dangerous Work"],
    "insalubridade": ["Insalubridade", "Unhealthy Work", "Health Hazard"],
    # TECNOLOGIA ESPECÍFICA
    "cloud": ["Cloud", "Nuvem", "Cloud Computing", "Cloud Service"],
    "saas": ["SaaS", "Software as a Service", "Cloud Software"],
    "paas": ["PaaS", "Platform as a Service", "Cloud Platform"],
    "iaas": ["IaaS", "Infrastructure as a Service", "Cloud Infrastructure"],
    "devops": ["DevOps", "Development Operations", "Dev Ops"],
    "agile": ["Agile", "Ágil", "Metodologia Ágil", "Agile Methodology"],
    "scrum": ["Scrum", "Framework Scrum", "Scrum Method"],
    "kanban": ["Kanban", "Metodologia Kanban", "Kanban Board"],
    "sprint": ["Sprint", "Iteration", "Development Sprint"],
    "repository": ["Repositório", "Repository", "Repo", "Code Repository"],
    "git": ["Git", "Version Control", "Source Control"],
    "github": ["GitHub", "Git Hub", "Code Platform"],
    "gitlab": ["GitLab", "Git Lab"],
    "bitbucket": ["Bitbucket", "Bit Bucket"],
    "docker": ["Docker", "Container", "Containerization"],
    "kubernetes": ["Kubernetes", "K8s", "Orchestration", "Container Orchestration"],
    "jenkins": ["Jenkins", "CI/CD", "Continuous Integration"],
    "terraform": ["Terraform", "Infrastructure as Code"],
    "ansible": ["Ansible", "Configuration Management"],
    "aws": ["AWS", "Amazon Web Services", "Amazon Cloud"],
    "azure": ["Azure", "Microsoft Azure", "Azure Cloud"],
    "gcp": ["GCP", "Google Cloud Platform", "Google Cloud"],
    "microservicos": ["Microserviços", "Microservices", "Micro Services"],
    "rest": ["REST", "RESTful", "REST API"],
    "graphql": ["GraphQL", "Graph QL"],
    "json": ["JSON", "JavaScript Object Notation"],
    "xml": ["XML", "Extensible Markup Language"],
    "yaml": ["YAML", "YAML Configuration"],
    "ssl_tec": ["SSL", "TLS", "Security Certificate"],
    "oauth": ["OAuth", "Authentication Protocol"],
    "jwt": ["JWT", "JSON Web Token"],
    "cdn": ["CDN", "Content Delivery Network"],
    "load_balancer": ["Load Balancer", "Balanceador de Carga"],
    # CONTABILIDADE
    "contabilidade": ["Contabilidade", "Accounting", "Bookkeeping"],
    "contador": ["Contador", "Accountant", "CPA"],
    "balanco": ["Balanço", "Balance Sheet", "Financial Statement"],
    "dre": ["DRE", "Demonstração do Resultado", "Income Statement"],
    "dfc": ["DFC", "Demonstração do Fluxo de Caixa", "Cash Flow Statement"],
    "dmpl": ["DMPL", "Demonstração das Mutações do Patrimônio Líquido"],
    "dva": ["DVA", "Demonstração do Valor Adicionado"],
    "razao": ["Razão", "General Ledger", "Ledger"],
    "diario": ["Diário", "Journal", "Accounting Journal"],
    "lancamento_contabil": ["Lançamento", "Entry", "Accounting Entry"],
    "debito_contabil": ["Débito", "Debit", "Debit Entry"],
    "credito_contabil": ["Crédito", "Credit", "Credit Entry"],
    "plano_contas": ["Plano de Contas", "Chart of Accounts", "Account Plan"],
    "centro_custo": ["Centro de Custo", "Cost Center", "Department Code"],
    "depreciacao": ["Depreciação", "Depreciation", "Asset Depreciation"],
    "amortizacao": ["Amortização", "Amortization", "Loan Amortization"],
    "provisao": ["Provisão", "Provision", "Reserve"],
    "accrual": ["Competência", "Accrual", "Accrual Basis"],
    "regime_caixa": ["Regime de Caixa", "Cash Basis", "Cash Accounting"],
    "sped": ["SPED", "Sistema Público de Escrituração Digital"],
    "ecf": ["ECF", "Escrituração Contábil Fiscal"],
    "ecd": ["ECD", "Escrituração Contábil Digital"],
    # TRIBUTOS E IMPOSTOS
    "imposto": ["Imposto", "Tax", "Taxation", "Levy"],
    "tributo": ["Tributo", "Tax", "Tribute", "Government Tax"],
    "icms": ["ICMS", "Tax on Circulation of Goods and Services"],
    "ipi": ["IPI", "Tax on Industrialized Products"],
    "iss": ["ISS", "Service Tax", "Municipal Service Tax"],
    "pis": ["PIS", "Social Integration Program"],
    "cofins": ["COFINS", "Social Security Financing Contribution"],
    "csll": ["CSLL", "Social Contribution on Net Profits"],
    "irpj": ["IRPJ", "Corporate Income Tax"],
    "irrf": ["IRRF", "Withholding Income Tax"],
    "inss_empresa": ["INSS Empresa", "Company Social Security"],
    "fgts_empresa": ["FGTS Empresa", "Company Severance Fund"],
    "simples": ["Simples", "Simplified Tax System", "Simples Nacional"],
    "lucro_real": ["Lucro Real", "Actual Profit", "Real Profit Taxation"],
    "lucro_presumido": ["Lucro Presumido", "Presumed Profit"],
    "mei": ["MEI", "Individual Microentrepreneur"],
    "microempresa": ["Microempresa", "Microenterprise", "Small Business"],
    "epp": ["EPP", "Empresa de Pequeno Porte", "Small Company"],
    "regime_tributario": ["Regime Tributário", "Tax System", "Tax Regime"],
    "aliquota": ["Alíquota", "Tax Rate", "Rate"],
    "base_calculo": ["Base de Cálculo", "Tax Base", "Calculation Base"],
    "isencao": ["Isenção", "Exemption", "Tax Exemption"],
    "reducao": ["Redução", "Reduction", "Tax Reduction"],
    "substituicao_tributaria": ["Substituição Tributária", "Tax Substitution"],
    # PROJETOS E GESTÃO
    "projeto": ["Projeto", "Project", "Initiative"],
    "gerenciamento": ["Gerenciamento", "Management", "Project Management"],
    "cronograma_projeto": ["Cronograma", "Schedule", "Project Timeline"],
    "milestone": ["Marco", "Milestone", "Key Milestone"],
    "entregavel": ["Entregável", "Deliverable", "Project Deliverable"],
    "stakeholder": ["Stakeholder", "Interessado", "Project Stakeholder"],
    "sponsor": ["Patrocinador", "Sponsor", "Project Sponsor"],
    "escopo": ["Escopo", "Scope", "Project Scope"],
    "requisito": ["Requisito", "Requirement", "Project Requirement"],
    "risco_projeto": ["Risco", "Risk", "Project Risk"],
    "issue": ["Problema", "Issue", "Project Issue"],
    "mudanca": ["Mudança", "Change", "Change Request"],
    "baseline": ["Baseline", "Linha de Base", "Project Baseline"],
    "gantt": ["Gantt", "Gráfico de Gantt", "Gantt Chart"],
    "pert": ["PERT", "Program Evaluation Review Technique"],
    "wbs": ["WBS", "Work Breakdown Structure", "Estrutura Analítica"],
    "pmo": ["PMO", "Project Management Office"],
    "kpi_projeto": ["KPI", "Key Performance Indicator", "Indicador"],
    "dashboard": ["Dashboard", "Painel", "Control Panel"],
    "report": ["Relatório", "Report", "Project Report"],
    # QUALIDADE E CERTIFICAÇÕES
    "iso": ["ISO", "International Organization for Standardization"],
    "iso_9001": ["ISO 9001", "Quality Management System"],
    "iso_14001": ["ISO 14001", "Environmental Management"],
    "iso_45001": ["ISO 45001", "Occupational Health and Safety"],
    "iso_27001": ["ISO 27001", "Information Security Management"],
    "seis_sigma": ["Seis Sigma", "Six Sigma", "Quality Improvement"],
    "lean": ["Lean", "Lean Manufacturing", "Lean Management"],
    "kaizen": ["Kaizen", "Continuous Improvement"],
    "pdca": ["PDCA", "Plan-Do-Check-Act", "Quality Cycle"],
    "dmaic": ["DMAIC", "Define-Measure-Analyze-Improve-Control"],
    "certificacao_qualidade": ["Certificação", "Certification", "Quality Certificate"],
    "auditoria_qualidade": ["Auditoria", "Audit", "Quality Audit"],
    "ncr": ["NCR", "Non-Conformity Report", "Não Conformidade"],
    "acao_corretiva": ["Ação Corretiva", "Corrective Action"],
    "acao_preventiva": ["Ação Preventiva", "Preventive Action"],
    "melhoria_continua": ["Melhoria Contínua", "Continuous Improvement"],
    # MEIO AMBIENTE E SUSTENTABILIDADE
    "meio_ambiente": ["Meio Ambiente", "Environment", "Environmental"],
    "sustentabilidade": ["Sustentabilidade", "Sustainability", "Sustainable"],
    "licenca_ambiental": ["Licença Ambiental", "Environmental License"],
    "impacto_ambiental": ["Impacto Ambiental", "Environmental Impact"],
    "gestao_residuos": ["Gestão de Resíduos", "Waste Management"],
    "reciclagem": ["Reciclagem", "Recycling", "Recycle"],
    "energia_renovavel": ["Energia Renovável", "Renewable Energy"],
    "carbono": ["Carbono", "Carbon", "Carbon Footprint"],
    "pegada_carbono": ["Pegada de Carbono", "Carbon Footprint"],
    "sustentavel": ["Sustentável", "Sustainable", "Green"],
    "verde": ["Verde", "Green", "Eco-friendly"],
    "esg": ["ESG", "Environmental Social Governance"],
    "responsabilidade_social": ["Responsabilidade Social", "Social Responsibility"],
    # COMUNICAÇÃO INTERNA
    "comunicacao": ["Comunicação", "Communication", "Internal Communication"],
    "reuniao": ["Reunião", "Meeting", "Conference"],
    "apresentacao": ["Apresentação", "Presentation", "Pitch"],
    "relatorio": ["Relatório", "Report", "Document"],
    "ata": ["Ata", "Minutes", "Meeting Minutes"],
    "memo": ["Memorando", "Memo", "Internal Memo"],
    "circular": ["Circular", "Circular Letter", "Company Notice"],
    "comunicado": ["Comunicado", "Notice", "Announcement"],
    "newsletter": ["Newsletter", "Company Newsletter"],
    "intranet": ["Intranet", "Internal Network", "Company Portal"],
    "portal": ["Portal", "Company Portal", "Internal Portal"],
    "video_conferencia": ["Videoconferência", "Video Conference", "Online Meeting"],
    "webinar": ["Webinar", "Online Seminar", "Web Seminar"],
}


def detect_column_types(df):
    """
    Retorna para cada coluna do DataFrame o seu 'tipo' (key do dicionário) OU None se não encontrado.
    Exemplo de saída: {'CEP': 'cep', 'Endereço': 'endereco', 'CNPJ': 'cnpj', ...}
    """
    col_map = {}
    for col in df.columns:
        col_norm = unidecode.unidecode(str(col)).lower().strip()
        found = None
        for tipo, sin_list in DOMAIN_SYNONYMS.items():
            for sin in sin_list:
                sin_norm = unidecode.unidecode(str(sin)).lower().strip()
                # Aceita igual ou inicia igual (ex: 'Endereço' pega 'Endereço Completo')
                if col_norm == sin_norm or col_norm.startswith(sin_norm):
                    found = tipo
                    break
            if found:
                break
        col_map[col] = found  # tipo (ex: 'cep') ou None
    return col_map
